services:
  quizly_web:
    build:
      context: .
      dockerfile: Dockerfile
    image: quizly:latest
    container_name: quizly_web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./media:/usr/src/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            gunicorn config.wsgi:application --bind 0.0.0.0:8001"